### ISSUE TITLE
actix-web update to 1.x

### ISSUE THREAD

**Issue by s-panferov** [HeroicKatora/oxide-auth#37]
# Project Improvement

`actix-web` 1.x has some breaking changes. The library and examples need to be updated to remain useful.

# Tracking pull request

 - [ ] A pull request (does not yet exist)

**Comment by asonix** [comment]
Here's something interesting I just realized: Actix Web 1.0 with the `secure-cookies` feature depends on ring 0.14, which is incompatible with ring 0.13... I'm not sure how to resolve this

**Comment by HeroicKatora** [comment]
Potential ways:

* Have multiple features that allow selecting a compatible version of `ring` in `oxide-auth`. Finally somewhat sane since frontends can each select their exclusive features.
* Remove the dependency on `ring`. This would be a very slightly breaking change as the HMAC key can currently be converted from a `ring` struct. The potential of `ring` is barely used so this doesn't require looking for another general purpose crypto library. But needs some auditing of that library, I believe the others are not as popular.

**Comment by asonix** [comment]
```toml
ring = { version = "0.14", optional = true }
ring13 = { version = "0.1.0", optional = true }
```

Using a ring shim crate doesn't work, even if both `ring` and `ring13` are optional dependencies.

**Comment by HeroicKatora** [comment]
It seems that all crates in a workspace need to lead to a single selection of packages and version, and linking collisions from native libraries are also checked across all these packages. Otherwise it would work to specify manually a SemVer range like so:

> ring = ">=0.13,<0.17"

Maybe we can 'just' get rid of the workspace and build each separately.

**Comment by HeroicKatora** [comment]
Hm, `0.14` has a breaking change to https://docs.rs/ring/0.14.0/ring/pbkdf2/fn.verify.html which is in use. This is not so simple, needs to be features.

**Comment by HeroicKatora** [comment]
Cheeky idea: turn `iterations` into a `NonZeroU32` and use `self.iterations.into()`. This should have the correct behaviour in all versions. Once it is a no-op and for `0.13` it selects `From<NonZeroU32> for u32`.

**Comment by asonix** [comment]
I've gotten rid of the workspace entirely on my box and i'm still not able to compile a package that optionally depends on ring13 and ring14

**Comment by HeroicKatora** [comment]
Cargo doesn't seem to like it, can't have conflicting optional dependencies it seems. The whole workspace needs to resolve to the same ring version though, as well. Maybe a separate directory just for testing both/all possible ring versions should be added outside the workspace. Then at least the current setup can stay.

**Comment by gzp-crey** [comment]
Any update on this issue ?

**Comment by asonix** [comment]
@gzp-crey there's a branch of this repo supporting actix 1.0, but it hasn't been released yet

**Comment by HeroicKatora** [comment]
Specifically, you can specify these dependencies for the moment:

```toml
[dependencies]
oxide-auth = { version = "0.5.0-preview.0", git = "https://github.com/HeroicKatora/oxide-auth/", branch = "next" }
oxide-auth-actix = { git = "https://github.com/HeroicKatora/oxide-auth/", branch = "next" }
```
